spring.application.name=ExpensesTracker
spring.datasource.url=jdbc:postgresql://localhost:5432/Expenses_Tracker
spring.datasource.username=postgres
spring.datasource.password=Hari@08082006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true